"""Build both ThermoLab site copies (EN + HE) into _site/.

    _site/index.html  -> redirect to /en/
    _site/en/...      -> English site
    _site/he/...      -> Hebrew site (RTL)

Each language is an independent MyST project built with BASE_URL=/<lang> so its internal
links resolve under that prefix.

Why there is no HTML post-processing here: the mystmd book theme is a hydrating React app
that rebuilds the document after load, discarding anything injected into the static HTML
(styles, scripts, added elements, and `lang`/`dir` attributes). Everything language-specific
therefore goes through configuration the theme itself honours — `site.options.style` for the
stylesheet (generated by scripts/build_css.py) and `site.options.logo_text` for the header
title. Known limitation of that trade-off: the theme's own chrome ("Search", "CONTENTS", …)
stays English on the Hebrew copy, and `<html lang>` is not language-tagged.

The two language copies do not link to each other; _site/index.html is the only chooser.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_css import generate as generate_css  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "_site"
LANGS = ("en", "he")

ROOT_REDIRECT = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ThermoLab</title>
<meta http-equiv="refresh" content="0; url=./en/">
<script>location.replace("./en/");</script>
</head>
<body>
<p><a href="./en/">English</a> &middot; <a href="./he/" lang="he">עברית</a></p>
</body>
</html>
"""


def myst_executable() -> str:
    exe = ROOT / "node_modules" / ".bin" / ("myst.cmd" if os.name == "nt" else "myst")
    if not exe.exists():
        sys.exit("mystmd not found — run `npm install` first")
    return str(exe)


def build_language(lang: str) -> Path:
    env = os.environ.copy()
    env["BASE_URL"] = f"/{lang}"
    print(f"[build_site] building {lang} (BASE_URL=/{lang}) ...")
    subprocess.run(
        [myst_executable(), "build", "--html"],
        cwd=ROOT / "content" / lang,
        env=env,
        check=True,
    )
    out = ROOT / "content" / lang / "_build" / "html"
    if not out.exists():
        sys.exit(f"expected build output missing: {out}")
    return out


def build_jupyterlite() -> None:
    """Bundle the notebooks into a browser-runnable JupyterLite app at _site/lite/.

    This is what lets a reader open a laboratory without installing anything: Pyodide runs
    the same `thermolab` code in the browser. It is a best-effort step — a missing or broken
    JupyterLite must not fail the site build, since the pages themselves carry static
    figures and local-run instructions either way.
    """
    print("[build_site] building JupyterLite bundle ...")
    result = subprocess.run(
        [sys.executable, "-m", "jupyter", "lite", "build"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("[build_site] JupyterLite build failed — the site is still usable:")
        print((result.stderr or result.stdout).strip()[-800:])
        return
    print(f"[build_site] JupyterLite -> {SITE / 'lite'}")


def main(skip_lite: bool = False) -> None:
    for path in generate_css():
        print(f"[build_site] stylesheet {path.relative_to(ROOT)}")

    builds = {lang: build_language(lang) for lang in LANGS}

    if SITE.exists():
        shutil.rmtree(SITE)
    SITE.mkdir()

    for lang in LANGS:
        shutil.copytree(builds[lang], SITE / lang)
        print(f"[build_site] {lang}: {len(list((SITE / lang).rglob('*.html')))} pages")

    (SITE / "index.html").write_text(ROOT_REDIRECT, encoding="utf-8")

    if not skip_lite:
        build_jupyterlite()

    print(f"[build_site] done -> {SITE}  (serve with: python -m http.server -d _site)")


if __name__ == "__main__":
    main(skip_lite="--no-lite" in sys.argv)
